name: Build Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
    
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: get version
      shell: bash
      run: echo PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) | cut -d- -f1 >> $GITHUB_ENV
    
    - name: Build and Test
      run: mvn -B package -X -T 4 --file pom.xml

  push-image:
    runs-on: ubuntu-latest
    needs: build
    env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          IMAGE_NAME: serfanrud/core-wallet-service
          # PROJECT_VERSION: ${{env.PROJECT_VERSION}}
          # FIXED_VERSION: ${{env.FIXED_VERSION}}
          LATEST_VERSION: latest
          GITHUB_SHA: ${{github.sha}}
    steps:
      - uses: actions/checkout@v3
      - name: docker-login
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build docker image 
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:$LATEST_VERSION

      - name: Docker push
        run: docker push $IMAGE_NAME:$LATEST_VERSION
  coverage:
    runs-on: ubuntu-latest
    needs: [build,push-image]
    steps:
      - name: Install dependencies
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: Run tests and collect coverage
        run: mvn -B test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    
    
    
    
